spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: lab-2
  h2:
    console:
      enabled: true
      path: /h2-console
