spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: lab-3

# Book Metadata API (OpenLibrary)
book:
  metadata:
    api:
      base-url: "https://openlibrary.org/wrong/path/for/demo"
      timeout: 5
