spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: lab-4

# Book Metadata API (OpenLibrary)
book:
  metadata:
    api:
      url: https://openlibrary.org
      timeout: 5